# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

FROM docker.io/golang:1.24 as build
RUN GOPROXY=direct GOBIN=/usr/local/bin/ go install github.com/public-transport/gtfsclean@latest


FROM docker.io/debian:bookworm-slim

ARG MOTIS_VERSION=v2.3.3

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends git python3-pip wget bzip2 rsync openssh-client && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* 
RUN rm /usr/lib/python3.*/EXTERNALLY-MANAGED && \
    pip3 install requests ruamel.yaml pycountry beautifulsoup4 lxml license-expression

COPY --from=build /usr/local/bin/gtfsclean /usr/local/bin/gtfsclean
RUN mkdir -p /opt/motis/ && \
    wget -qO - https://github.com/motis-project/motis/releases/download/${MOTIS_VERSION}/motis-linux-amd64.tar.bz2 | tar -C /opt/motis/ -jx
ENV PATH=/opt/motis:$PATH
