# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

FROM docker.io/debian:bookworm-slim

RUN apt-get update && apt-get install git python3-requests python3-jinja2 golang -y && apt clean

ADD https://github.com/motis-project/motis/releases/download/v0.11.18/motis-linux-amd64.tar.bz2 /opt/
RUN GOBIN=/usr/local/bin/ go install github.com/patrickbr/gtfstidy@latest
