# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

FROM docker.io/debian:bookworm-slim

ARG MOTIS_VERSION=v0.11.33
ARG USERNAME=transitous
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends git python3-requests python3-jinja2 golang wget bzip2 && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

RUN wget -qO - https://github.com/motis-project/motis/releases/download/${MOTIS_VERSION}/motis-linux-amd64.tar.bz2 | tar -C /opt/ -jx
RUN GOBIN=/usr/local/bin/ go install github.com/patrickbr/gtfstidy@25d4d6d1079a5926d9a558546bbe36d5b4cdb45f
ENV PATH=/opt/motis:$PATH

# Create the user / set user rights
RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    mkdir /workspace && chown -R $USER_UID:$USER_GID /workspace && \
    chown -R $USER_UID:$USER_GID /opt/motis

USER ${USERNAME}
