# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

FROM docker.io/golang:1.25 as build
RUN GOPROXY=direct GOBIN=/usr/local/bin/ go install github.com/public-transport/gtfsclean@latest

FROM docker.io/debian:bookworm-slim

ARG MOTIS_VERSION=v2.8.3
ARG USERNAME=transitous
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends git python3-pip wget bzip2 rsync openssh-client age && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* && \
    rm /usr/lib/python3.*/EXTERNALLY-MANAGED
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN mkdir -p /opt/motis/ && \
    wget -qO - https://github.com/motis-project/motis/releases/download/${MOTIS_VERSION}/motis-linux-amd64.tar.bz2 | tar -C /opt/motis/ -jx
COPY --from=build /usr/local/bin/gtfsclean /usr/local/bin/gtfsclean
ENV PATH=/opt/motis:$PATH

# Create the user / set user rights
RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    mkdir /workspace && chown -R $USER_UID:$USER_GID /workspace && \
    chown -R $USER_UID:$USER_GID /opt/motis

USER ${USERNAME}
