# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Install pyosmium-up-to-date
  apt:
    update_cache: true
    name:
     - pyosmium
  when: motis_primary is not defined or not motis_primary

- name: Create MOTIS group
  group:
    name: motis

- name: Create MOTIS user
  user:
    name: motis
    group: motis

- name: Create MOTIS directory
  file:
    path: /opt/motis/
    state: directory

- name: Create directory for imported data
  file:
    path: /var/cache/transitous/out/
    state: directory

- name: Set motis version
  set_fact:
    motis_version: v2.11.0

- name: Unpack MOTIS
  unarchive:
    src: https://github.com/public-transport/transitous/releases/download/motis-{{motis_version}}/motis-release-skylake-avx512.tar.bz2
    dest: /opt/motis/
    remote_src: yes

- name: Create motis source dir
  delegate_to: localhost
  ansible.builtin.file:
    path: /var/cache/motis-git
    state: directory
    owner: algolocal
    group: algolocal
    mode: 0775
  when: gpu_build is defined and gpu_build

- name: Get motis source
  delegate_to: localhost
  ansible.builtin.git:
    repo: 'https://github.com/motis-project/motis.git'
    dest: /var/cache/motis-git
    version: "{{motis_version}}"
  when: gpu_build is defined and gpu_build

- name: Install build deps
  delegate_to: localhost
  become: true
  apt:
    update_cache: true
    name:
     - g++-15
     - gcc-15
     - cmake
     - ninja-build
  when: gpu_build is defined and gpu_build

- name: motis gpu build
  ansible.builtin.script: gpu-build.sh
  delegate_to: localhost
  when: gpu_build is defined and gpu_build

- name: Copy motis gpu binary
  copy:
    src: /var/cache/motis-git/build/cuda/motis
    dest: /opt/motis/motis
  when: gpu_build is defined and gpu_build

- name: Create MOTIS runtime directory
  file:
    path: /var/lib/motis
    owner: motis
    group: motis
    state: directory

- name: Copy MOTIS systemd service
  copy:
    src: motis.service
    dest: /etc/systemd/system/motis.service
  when: motis_primary is defined and motis_primary

- name: Enable motis systemd service
  systemd:
    name: motis.service
    enabled: true
    state: started
    masked: false
    daemon_reload: true
  when: motis_primary is defined and motis_primary

- name: Install motis-update-feeds script
  template:
    src: motis-update-feeds.sh
    dest: /usr/local/bin/motis-update-feeds
    mode: '0755'
  when: motis_primary is defined and motis_primary

- name: Install secondary motis-update-feeds script
  template:
    src: motis-update-feeds-secondary.sh
    dest: /usr/local/bin/motis-update-feeds
    mode: '0755'
  when: motis_primary is not defined or not motis_primary

- name: Install motis-update-feeds service
  template:
    src: "motis-update-feeds.service"
    dest: /etc/systemd/system/
    mode: '644'

- name: Install motis-update-feeds timer
  template:
    src: "motis-update-feeds.timer"
    dest: /etc/systemd/system/
    mode: '644'
  when: motis_update_time is defined

- name: Enable motis-update-feeds timer
  systemd:
    name: motis-update-feeds.timer
    enabled: true
    masked: false
    daemon_reload: true
    state: started
  when: motis_update_time is defined
