-- autogenerated by generate_colors.py
-- SPDX-FileCopyrightText: contributors of https://github.com/Traewelling/line-colors
-- SPDX-License-Identifier: CC0-1.0

local colors = {
    ["Braunschweiger Verkehrs-GmbH"] = {
        ["1"] = { color = 0xe2000a, text_color = 0xffffff },
        ["10"] = { color = 0xe2000a, text_color = 0xffffff },
        ["1E"] = { color = 0xe2000a, text_color = 0xffffff },
        ["2"] = { color = 0x93c019, text_color = 0xffffff },
        ["2E"] = { color = 0x93c019, text_color = 0xffffff },
        ["3"] = { color = 0x006430, text_color = 0xffffff },
        ["3E"] = { color = 0x006430, text_color = 0xffffff },
        ["4"] = { color = 0x009ee2, text_color = 0xffffff },
        ["411"] = { color = 0xb1a85c, text_color = 0xffffff },
    },
}
return colors
