-- SPDX-FileCopyrightText: Volker Krause <vkrause@kde.org>
-- SPDX-License-Identifier: AGPL-3.0-or-later

-- MOTIS class enum values
AIRPLANE = 0
HIGHSPEED_RAIL = 1
LONG_DISTANCE = 2
COACH = 3
NIGHT_RAIL = 4
REGIONAL_FAST_RAIL = 5
REGIONAL_RAIL = 6
SUBURBAN = 7
SUBWAY = 8
TRAM = 9
BUS = 10
FERRY = 11
CABLE_CAR = 12
FUNICULAR = 13
AERIAL_LIFT = 14
OTHER = 15
