# SPDX-FileCopyrightText: 2025 Traines <git@traines.eu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# These are additional feed entries solely used for the feed proxy. Secrets for most feeds are now stored directly in the feed jsons.
# some GBFS feeds redirect to different domains, we need to whitelist them here

xx-api.gbfs.ecovelo.mobi:
  gbfs: true
  url: https://api.gbfs.ecovelo.mobi
xx-api.gbfs.v3.0.ecovelo.mobi:
  gbfs: true
  url: https://api.gbfs.v3.0.ecovelo.mobi
xx-api.omega.fifteen.eu:
  gbfs: true
  url: https://api.omega.fifteen.eu
xx-api.saint-etienne-metropole.fr:
  gbfs: true
  url: https://api.saint-etienne-metropole.fr
xx-api.voiapp.io:
  gbfs: true
  url: https://api.voiapp.io
xx-backend.citiz.fr:
  gbfs: true
  url: https://backend.citiz.fr
xx-bdx.mecatran.com:
  gbfs: true
  url: https://bdx.mecatran.com
xx-clermontferrand.publicbikesystem.net:
  gbfs: true
  url: https://clermontferrand.publicbikesystem.net
xx-data.grandlyon.com:
  gbfs: true
  url: https://data.grandlyon.com
xx-data.mulhouse-alsace.fr:
  gbfs: true
  url: https://data.mulhouse-alsace.fr
xx-data.optymo.fr:
  gbfs: true
  url: https://data.optymo.fr
xx-download.data.grandlyon.com:
  gbfs: true
  url: https://download.data.grandlyon.com
xx-eu.ftp.opendatasoft.com:
  gbfs: true
  url: https://eu.ftp.opendatasoft.com
xx-fr.getaround.com:
  gbfs: true
  url: https://fr.getaround.com
xx-gateway.prod.partners-fs37hd8.zoov.site:
  gbfs: true
  url: https://gateway.prod.partners-fs37hd8.zoov.site
xx-gateway.prod.zoov.io:
  gbfs: true
  url: https://gateway.prod.zoov.io
xx-gbfs.clem.mobi:
  gbfs: true
  url: https://gbfs.clem.mobi
xx-gbfs.getapony.com:
  gbfs: true
  url: https://gbfs.getapony.com
xx-gbfs.omega.fifteen.eu:
  gbfs: true
  url: https://gbfs.omega.fifteen.eu
xx-gbfs.partners.fifteen.eu:
  gbfs: true
  url: https://gbfs.partners.fifteen.eu
xx-gbfs.theta.fifteen.eu:
  gbfs: true
  url: https://gbfs.theta.fifteen.eu
xx-mds.bird.co:
  gbfs: true
  url: https://mds.bird.co
xx-media.ilevia.fr:
  gbfs: true
  url: https://media.ilevia.fr
xx-mobi-iti-nam.okina.fr:
  gbfs: true
  url: https://mobi-iti-nam.okina.fr
xx-stables.donkey.bike:
  gbfs: true
  url: https://stables.donkey.bike
xx-stce.transdev-hdf.fr:
  gbfs: true
  url: https://stce.transdev-hdf.fr
xx-valence.publicbikesystem.net:
  gbfs: true
  url: https://valence.publicbikesystem.net
xx-velib-metropole-opendata.smovengo.cloud:
  gbfs: true
  url: https://velib-metropole-opendata.smovengo.cloud
xx-www.mobility-parc.net:
  gbfs: true
  url: https://www.mobility-parc.net
