# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM docker.io/debian:bookworm-slim

RUN apt-get update && \
    apt-get install ansible systemd systemd-sysv -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

COPY ./ /var/lib/transitous/ansible

RUN passwd --delete root

RUN cd /var/lib/transitous/ansible/ && ansible-playbook motis-container.yml

CMD [ "/usr/sbin/init" ]
