# SPDX-FileCopyrightText: 2025 Traines <git@traines.eu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# ansible-playbook -e "feed_proxy_host=proxy.example.com" -e "feed_proxy_conf_dir=/tmp/" feed-proxy.yml

# run install-key.yml once or manually get the feed proxy age private key in roles/feed-proxy/templates/feed-proxy.key and put it in decrypted form to $TRANSITOUS_FEED_PROXY_KEY_FILE
# encrypting new secrets to put directly into feed jsons as values:
# echo AGE-ENCRYPTED:$(echo -n "my-api-key" | age -r age1xpexzyk4k608tsccev20d7uakptkmgxr4nc8s0azzywkgtz86aaqsdryr4 | base64 -w0)

- name: Set up feed proxy server
  hosts: localhost
  roles:
    - feed-proxy
