#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

import argparse
import json
import toml
import metadata
import os
import shutil
import sys
import transitland
import mobilitydatabase

from ruamel.yaml import YAML
from typing import Any
from pathlib import Path
from utils import eprint, decrypt_if_necessary
from urllib.parse import quote

FEED_PROXY="https://rt.triptix.tech"

def find_motis_asset(asset_name: str):
    motis_path = shutil.which("motis")
    if not motis_path:
        return None
    asset_path = os.path.abspath(os.path.join(motis_path, "..", asset_name))
    return asset_path if os.path.exists(asset_path) else None

def check_file_exist_in_out_folder(file_name: str):
    return os.path.isfile(os.path.join("out", file_name))

def to_motis_rt_spec(spec: str) -> str:
    match spec:
        case 'gtfs-rt': return 'gtfsrt'
        case 'siri-json': return 'siri_json'
    return spec

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Transitous MOTIS configuration generator.')
    parser.add_argument('--import-only', action='store_true', help='Generate configuration for importing only.')
    parser.add_argument('--skip-missing-files', action='store_true', help='Do not generate entry for missing GTFS files')
    parser.add_argument('--feed-proxy', action='store_true', help='Generate configuration for the feed proxy.')
    parser.add_argument('regions', type=str, help='Only generate configuration for the given region(s) (leave empty for all regions, globs are supported)', nargs="*")
    arguments = parser.parse_args()

    feed_dir = Path("feeds/")
    script_dir = Path("scripts/")

    atlas = transitland.Atlas.load(Path("transitland-atlas/"))
    mdb = mobilitydatabase.Database.load()

    # TODO backward compatibility, remove this in a few months
    while "full" in arguments.regions:
        print("Ignoring legacy option 'full', this is the default now.")
        arguments.regions.remove("full")

    feeds = []
    regions: list[tuple[str, metadata.Region]] = []
    if len(arguments.regions) == 0:
        feeds = list(feed_dir.glob("*.json"))
    else:
        for region in arguments.regions:
            feeds += list(feed_dir.glob(f"{region}.json"))

    for feed in sorted(feeds):
        region_name = feed.name[:feed.name.rfind(".")]
        regions.append((region_name, metadata.Region(json.load(open(feed, "r")))))

    ignored_feeds = set() # for feeds ignored due to missing file

    with open("configs/motis/config.yml") as f:
        yaml = YAML(typ="rt")

        config = yaml.load(f)
        config.yaml_set_comment_before_after_key(
            "server",
            before="This file is automatically generated by ./src/generate-motis-config.py from motis/config.yml",
        )

        web_folder = find_motis_asset("ui/")
        if web_folder:
            config["server"]["web_folder"] = web_folder

        if arguments.import_only:
            config.pop("tiles")
        else:
            tile_profile = find_motis_asset("tiles-profiles/full.lua")
            if tile_profile and "tiles" in config:
                config["tiles"]["profile"] = tile_profile

        config["timetable"].yaml_set_comment_before_after_key(
            "datasets", before="Modified by generate-motis-config.py"
        )
        config["timetable"]["datasets"] = {}
        config["gbfs"]["feeds"] = {}
        config["gbfs"]["proxy"] = FEED_PROXY

        for feed in sorted(feeds):
            with open(feed, "r") as f:
                parsed = json.load(f)
                region = metadata.Region(parsed)

                metadata_filename = feed.name
                region_name = metadata_filename[: metadata_filename.rfind(".")]

                for source in region.sources:
                    schedule_name = f"{region_name}-{source.name}"

                    if source.skip:
                        continue

                    resolved_sources = []
                    match source:
                        case metadata.TransitlandSource():
                            resolved_sources = atlas.sources_by_id(source)
                            if not resolved_sources:
                                eprint("Error: Could not resolve", source.transitland_atlas_id)
                                sys.exit(1)
                        case metadata.MobilityDatabaseSource():
                            resolved_source = mdb.source_by_id(source)
                            if not resolved_source:
                                eprint("Error: Could not resolve", source.mdb_id)
                                sys.exit(1)
                            resolved_sources = [resolved_source]
                        case _:
                            resolved_sources = [source]

                    for source in resolved_sources:
                        use_original_url = isinstance(source, metadata.UrlSource) and not source.use_feed_proxy
                        if arguments.feed_proxy and use_original_url and source.spec != "gbfs":
                            continue
                        if arguments.feed_proxy:
                            use_original_url = True
                        match source.spec:
                            case source.spec if source.spec in ["gtfs", "netex"]:
                                schedule_file = \
                                    f"{region_name}_{source.name}.{source.spec}.zip"
                                name = f"{region_name}-{source.name}"
                                if (not arguments.skip_missing_files) or check_file_exist_in_out_folder(schedule_file):
                                    config["timetable"]["datasets"][name] = \
                                        {
                                            "path": schedule_file,
                                            "extend_calendar": source.extend_calendar
                                        }

                                    if source.default_timezone is not None:
                                        config["timetable"]["datasets"][name]["default_timezone"] = source.default_timezone

                                    if source.enable_crowd_sourced_realtime:
                                        if "rt" not in config["timetable"]["datasets"][name]:
                                            config["timetable"]["datasets"][name]["rt"] = []

                                        config["timetable"]["datasets"][name]["rt"].append({"url": f"http://crowdsourcing.transitous.org/gtfsrt/{name}/trip-updates.pb" })

                                    if source.script is not None:
                                        if not os.path.exists(os.path.join(script_dir, source.script)):
                                            eprint(f"Error: Import script {source.script} for {name} could not be found.")
                                            sys.exit(1)
                                        config["timetable"]["datasets"][name]["script"] = f"scripts/{source.script}"
                                else:
                                    print("Warning: Skipping " + name + " as " + schedule_file + " is missing.")
                                    ignored_feeds.add(name)

                            case source.spec if isinstance(source, metadata.UrlSource) and source.spec in ["gtfs-rt", "siri", "siri-json"]:
                                name = f"{region_name}-{source.name}"
                                if name not in config["timetable"]["datasets"]:
                                    if arguments.skip_missing_files:  # Probably the static feed was not downloaded
                                        continue
                                    eprint(
                                        "Error: The name of a realtime (gtfs-rt) "
                                        + "feed needs to match the name of its "
                                        + "static base feed defined before the "
                                        + "realtime feed. Found nothing "
                                        + "belonging to",
                                        source.name,
                                    )
                                    sys.exit(1)

                                if "rt" not in config["timetable"]["datasets"][name]:
                                    config["timetable"]["datasets"][name]["rt"] = []

                                rt_feed: dict[str, Any] = {
                                    "url": decrypt_if_necessary(source.url) if use_original_url else FEED_PROXY + '/feed/' + quote(name) + "-" + str(len(config["timetable"]["datasets"][name]["rt"])),
                                    "protocol": to_motis_rt_spec(source.spec)
                                }

                                if source.headers and use_original_url:
                                    rt_feed["headers"] = {}
                                    for key, value in source.headers.items():
                                        rt_feed["headers"][key] = decrypt_if_necessary(value)

                                config["timetable"]["datasets"][name]["rt"] \
                                        .append(rt_feed)

                                if source.derive_trip_updates:
                                    config["timetable"]["datasets"][name]["rt"].append({
                                        "url": f"https://crowdsourcing.transitous.org/gtfsrt/{name}/trip-updates.pb",
                                        "protocol": "gtfsrt"
                                    })

                            case "gbfs" if isinstance(source, metadata.UrlSource):
                                name = f"{region_name}-{source.name}"
                                config["gbfs"]["feeds"][name] = {"url": decrypt_if_necessary(source.url) if use_original_url else FEED_PROXY + '/feed/' + quote(name)}
                                if source.headers and use_original_url:
                                    config["gbfs"]["feeds"][name]["headers"] = {}
                                    for key, value in source.headers.items():
                                        config["gbfs"]["feeds"][name]["headers"][key] = decrypt_if_necessary(value)

        if arguments.feed_proxy:
            with open("/tmp/feed-proxy-vars.yml", "w") as fo:
                feed_vars = {}
                for key in config["timetable"]["datasets"]:
                    if not "rt" in config["timetable"]["datasets"][key]:
                        continue
                    for i, rt_feed in enumerate(config["timetable"]["datasets"][key]["rt"]):
                        feed_vars[key + '-' + str(i)] = rt_feed
                for key in config["gbfs"]["feeds"]:
                    feed_vars[key] = config["gbfs"]["feeds"][key]
                    feed_vars[key]['gbfs'] = True
                yaml.dump(feed_vars, fo)    
        else:
            with open("out/config.yml", "w") as fo:
                yaml.dump(config, fo)

    # copy scripts
    shutil.rmtree("out/scripts", ignore_errors=True)
    shutil.copytree(script_dir, "out/scripts")

    with open("configs/gps-collector/config.toml", "r") as f:
        config = toml.load(f)
        config["feeds"] = {}

        for (region_name, region) in regions:
            for source in region.sources:
                if source.enable_crowd_sourced_realtime:
                    config["feeds"][f"{region_name}-{source.name}"] = {}

        if not os.path.exists("out/gps-collector/"):
            os.makedirs("out/gps-collector/")

        with open("out/gps-collector/config.toml", "w") as fo:
            toml.dump(config, fo)

    with open("configs/delay-tracker/config.toml", "r") as f:
        config = toml.load(f)
        config["feeds"] = {}

        for (region_name, region) in regions:
            for source in region.sources:
                if source.enable_crowd_sourced_realtime:
                    config["feeds"][f"{region_name}-{source.name}"] = {
                        "gtfs_url": f"../{region_name}_{source.name}.gtfs.zip",
                        "gtfsrt_url": f"http://10.11.1.1:5001/gtfsrt/{region_name}-{source.name}/vehicle-positions.pb"
                    }

                match source:
                    case metadata.UrlSource():
                        if source.derive_trip_updates:
                            config["feeds"][f"{region_name}-{source.name}"] = {
                                "gtfs_url": f"../{region_name}_{source.name}.gtfs.zip",
                                "gtfsrt_url": source.url
                            }

        if not os.path.exists("out/delay-tracker/"):
            os.makedirs("out/delay-tracker/")

        with open("out/delay-tracker/config.toml", "w") as fo:
            toml.dump(config, fo)
