# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

when:
  - event: push
    branch: [main, work/jbb/woodpecker]
    path:
      - 'feeds/*'
      - 'src/*'
      - 'ci/*'
      - 'ci/container/*'
      - 'motis/*'
      - '.woodpecker/*.yml'
  - event: cron
    cron: daily-import

steps:
  fetch:
    image: ghcr.io/public-transport/transitous/import:latest
    pull: true
    environment:
      GITHUB_TOKEN:
        from_secret: github_issues_token
    commands:
      - git submodule update --init --checkout --remote
      - ./ci/fetch-feeds.py timer
  import:
    image: ghcr.io/public-transport/transitous/import:latest
    pull: true
    commands:
      - motis --version
      - rm out/data -rf
      - ./src/generate-attribution.py
      - ./src/generate-motis-config.py import
      - cd out && motis import -c config.ini > motis-import.log && rm motis-import.log && cd ..
      - src/generate-motis-config.py full
  push:
    image: ghcr.io/public-transport/transitous/import:latest
    environment:
      RSYNC_PRIVATE_KEY:
        from_secret: RSYNC_PRIVATE_KEY
    commands:
      - echo "$${RSYNC_PRIVATE_KEY}" > deploy_key
      - chmod 600 ./deploy_key
      - "rsync -avz --progress --delete -e 'ssh -i ./deploy_key -p 2222 -o StrictHostKeyChecking=no' out/data/*.bin rsync@crunchy.spline.de:data/"
      - "rsync -avz --progress --delete -e 'ssh -i ./deploy_key -p 2222 -o StrictHostKeyChecking=no' out/config.yml rsync@crunchy.spline.de:data/"
      - rm deploy_key
