# SPDX-FileCopyrightText: 2025 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

server {
    listen 80;

    location /downloads/ {
        alias /var/cache/transitous/downloads/;
        autoindex on;
    }

    location /out/ {
        alias /var/cache/transitous/out/;
        autoindex on;
    }
}
