# SPDX-FileCopyrightText: 2024 Lars Röglin <git@parttimedatascientist.de>
# SPDX-License-Identifier: CC0-1.0

name: Deploy mkdocs-site to GH-Pages

on:
  push:
    branches:
      - main
# Run only if mkdocs-site folder is touched
# Other update is not necessary as the site is also
# updated in the data-pipeline.yml workflow
    paths:
      - mkdocs-site
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy_mkdocs_site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
          
      - name: Restore cached licenses.md
        uses: actions/cache/restore@v4
        with:
          path: |
            mkdocs-site/docs/licenses.md
          key: licenses-
          restore-keys: |
            licenses-

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs
      - run: mkdocs gh-deploy -f mkdocs-site/mkdocs.yml --force
